# Generated by Django 2.0.5 on 2018-08-08 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_val', models.CharField(max_length=30, verbose_name='颜色名称')),
                ('diy_val', models.CharField(max_length=60, verbose_name='颜色值')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=120, verbose_name='语言名称')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=120, verbose_name='页面标识')),
                ('flag', models.CharField(max_length=120, verbose_name='文字标识')),
                ('content', models.TextField(verbose_name='具体内容')),
                ('lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Lang', verbose_name='所属语言')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
    ]
