# Generated by Django 2.0.5 on 2018-08-08 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc
import vcr_apps.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KouZa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=60, verbose_name='姓')),
                ('first_name', models.CharField(max_length=123, verbose_name='名')),
                ('name', models.CharField(max_length=247, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=60, null=True, verbose_name='电话')),
                ('face', models.ImageField(default='def_face.jpg', upload_to=vcr_apps.user.models.upload_to_kouza, verbose_name='用户头像')),
                ('status', models.NullBooleanField(choices=[(True, '可用'), (None, '默认'), (False, '不可用')], default=True, verbose_name='状态')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='KouZaCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_kuukann', models.CharField(blank=True, max_length=247, null=True, verbose_name='默认空间')),
                ('lang', models.CharField(blank=True, max_length=60, null=True, verbose_name='语言')),
                ('keep_day', models.SmallIntegerField(default=30, verbose_name='回收站保留天数')),
                ('layout', models.CharField(blank=True, max_length=60, null=True, verbose_name='排列方式')),
                ('auth_num', models.SmallIntegerField(choices=[(0, '特殊身份'), (1, '未知'), (2, '新手'), (3, '老用户'), (4, '尊贵身份')], default='0', verbose_name='账号身份')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 194053, tzinfo=utc), verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 194053, tzinfo=utc), verbose_name='最近更新时间')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuuk_pwd', models.CharField(default='None', max_length=247, verbose_name='空间密码')),
                ('ctrl_pwd', models.CharField(default='None', max_length=247, verbose_name='功能控制密码')),
                ('is_tell', models.NullBooleanField(choices=[(True, '安全'), (False, '不安全'), (None, '未知')], default=False, verbose_name='号码是否已验证')),
                ('is_mail', models.NullBooleanField(choices=[(True, '安全'), (False, '不安全'), (None, '未知')], default=False, verbose_name='邮箱是否已验证')),
                ('which_jm', models.SmallIntegerField(blank=True, default='1_2_3_4_5_6', null=True, verbose_name='哪些需要加密')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SafeAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='你最喜欢谁，虚拟 or 现实的人物当中？', max_length=247, verbose_name='问题')),
                ('answer', models.CharField(default='这是我的秘密', max_length=123, verbose_name='答案')),
                ('status', models.NullBooleanField(choices=[(True, '可用'), (None, '默认'), (False, '不可用')], default=True, verbose_name='状态')),
                ('safe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Safe', verbose_name='安全性为')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shen', models.NullBooleanField(choices=[(True, '省流模式'), (False, '正常模式'), (None, '待机')], default=False, verbose_name='是否开启省流模式')),
                ('is_doh', models.NullBooleanField(choices=[(True, '原图模式'), (False, '均衡模式'), (None, '缩略图模式')], default=True, verbose_name='是否开启高质量下载模式')),
                ('comp_ro', models.SmallIntegerField(default=2166, verbose_name='压缩阈值')),
                ('is_zhe', models.BooleanField(choices=[(True, '折叠'), (False, '展开'), (None, '隐藏')], default=False, verbose_name='是否折叠底部')),
                ('def_layout', models.CharField(choices=[('max', '最大显示'), ('block', '块状布局'), ('grid', '栅格布局')], default='grid', max_length=60, verbose_name='默认布局模式')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(choices=[('teal', '水绿'), ('red', '红色'), ('yellow', '黄色'), ('green', '绿色'), ('pink', '粉色'), ('orange', '橙色'), ('blue', '蓝色'), ('purple', '紫色'), ('violet', '紫罗兰'), ('brown', '棕色'), ('grey', '灰色'), ('olive', '橄榄')], default='pink', max_length=30, verbose_name='主题颜色')),
                ('diy_color', models.CharField(choices=[('rgba(255, 174, 200, ', '粉色'), ('rgba(0, 168, 243, ', '蓝色'), ('rgba(255, 242, 0, ', '黄色'), ('rgba(14, 209, 69, ', '绿色'), ('rbga(236, 28, 36, ', '红色'), ('rgba(140, 255, 251, ', '水绿'), ('rgba(255, 202, 24, ', '金色'), ('rgba(196, 255, 14, ', '浅绿'), ('rgba(255, 127, 39, ', '橙色'), ('rgba(63, 72, 204, ', '靛蓝'), ('rgba(185, 122, 86, ', '褐色'), ('rgba(253, 236, 166, ', '浅黄'), ('rgba(136, 0, 27, ', '深红'), ('rgba(184, 61, 186, ', '紫色'), ('rgba(88, 88, 88, ', '灰色'), ('rgba(195, 195, 195, ', '浅灰')], default='rgba(255, 174, 200, ', max_length=60, verbose_name='样式颜色')),
                ('name', models.CharField(default='VcrT', max_length=120, verbose_name='网站名称')),
                ('bg_img', models.ImageField(default='def_face.jpg', upload_to=vcr_apps.user.models.upload_to_vcr, verbose_name='网站背景')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='kouza',
            name='kouza_ctrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.KouZaCtrl', verbose_name='所属网站配置'),
        ),
        migrations.AddField(
            model_name='kouza',
            name='safe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Safe', verbose_name='所属安全性'),
        ),
        migrations.AddField(
            model_name='kouza',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Setting', verbose_name='所属设置'),
        ),
        migrations.AddField(
            model_name='kouza',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Style', verbose_name='所属个性化'),
        ),
    ]
