# Generated by Django 2.0.5 on 2018-08-08 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc
import vcr_apps.kuukann.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='图片名称')),
                ('w', models.SmallIntegerField(blank=True, null=True, verbose_name='原图宽')),
                ('h', models.SmallIntegerField(blank=True, null=True, verbose_name='原图高')),
                ('px', models.IntegerField(blank=True, null=True, verbose_name='总像素大小')),
                ('fmt', models.CharField(max_length=30, verbose_name='图片格式')),
                ('ratio', models.FloatField(verbose_name='压缩比率')),
                ('content', models.TextField(verbose_name='内容')),
                ('comp_time', models.FloatField(verbose_name='压缩耗时(毫秒)')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.SmallIntegerField(blank=True, null=True, verbose_name='宽')),
                ('height', models.SmallIntegerField(blank=True, null=True, verbose_name='高')),
                ('status', models.NullBooleanField(choices=[(True, '可用'), (None, '未知'), (False, '不可用')], default=True, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 211009, tzinfo=utc), verbose_name='创建时间')),
                ('tiny_img', models.ImageField(upload_to=vcr_apps.kuukann.models.upload_to_tiny_img, verbose_name='美图')),
                ('has_full', models.BooleanField(default=False, verbose_name='是否有原图')),
                ('full_img', models.ImageField(blank=True, default=None, null=True, upload_to=vcr_apps.kuukann.models.upload_to_full_img, verbose_name='原图片')),
                ('less_img', models.ImageField(blank=True, default=None, null=True, upload_to=vcr_apps.kuukann.models.upload_to_less_img, verbose_name='缩略图')),
                ('kouza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.KouZa', verbose_name='所属用户')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImgMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='- 空白 -', verbose_name='内容')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuukann.Img', verbose_name='所属美图')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='KuuKann',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='空间名称')),
                ('index', models.SmallIntegerField(default=0, verbose_name='排序索引')),
                ('mark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('status', models.NullBooleanField(choices=[(True, '可用'), (None, '未知'), (False, '不可用')], default=True, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 206989, tzinfo=utc), verbose_name='创建时间')),
                ('kouza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.KouZa', verbose_name='所属用户')),
            ],
            options={
                'db_table': 'kuukann',
            },
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(choices=[('create_date', '最早'), ('-create_date', '最新')], default='create_date', max_length=60, verbose_name='排序名称')),
                ('layout_name', models.CharField(choices=[('max', '最大幅度显示'), ('block', 'Win10照片应用里的块状布局'), ('grid', '栅格系统均匀布局')], default='grid', max_length=60, verbose_name='排列名称')),
                ('diy_w', models.FloatField(default=1, verbose_name='自定义宽')),
                ('diy_h', models.FloatField(default=1, verbose_name='自定义高')),
                ('grid_name', models.CharField(choices=[('two', '每行8项'), ('four', '每行4项'), ('eight', '每行2项'), ('sixteen', '每行1项')], default='four', max_length=60, verbose_name='栅格名称')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=247, verbose_name='相册名称')),
                ('image', models.ImageField(upload_to=vcr_apps.kuukann.models.upload_to_pic, verbose_name='相册封面')),
                ('status', models.NullBooleanField(choices=[(True, '可用'), (None, '未知'), (False, '不可用')], default=True, verbose_name='状态')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 209017, tzinfo=utc), verbose_name='创建时间')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 209017, tzinfo=utc), verbose_name='最近更新时间')),
                ('kouza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.KouZa', verbose_name='所属用户')),
                ('kuukann', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuukann.KuuKann', verbose_name='所属空间')),
                ('layout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuukann.Layout', verbose_name='所属排列')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PicMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='（unknow）', max_length=200, verbose_name='作者们')),
                ('content', models.TextField(blank=True, default='（nothing）', verbose_name='相册介绍')),
                ('down_mark', models.CharField(blank=True, max_length=200, null=True, verbose_name='下载链接')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 210011, tzinfo=utc), verbose_name='创建时间')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RatioL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.FloatField(verbose_name='宽高比例')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateField(verbose_name='时间序列')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuukann.Pic', verbose_name='所属相册'),
        ),
    ]
