# Generated by Django 2.0.5 on 2018-08-08 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kuukann', '0002_auto_20180808_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 12, 24, 37, 172505, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='kuukann',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 12, 24, 37, 168547, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 12, 24, 37, 170511, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 12, 24, 37, 170511, tzinfo=utc), verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='picmsg',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 12, 24, 37, 171508, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
