# Generated by Django 2.0.5 on 2018-08-08 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kuukann', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_flag', models.CharField(max_length=30, verbose_name='回收标志')),
                ('false_date', models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 5, 50, 213002, tzinfo=utc), verbose_name='放入时间')),
                ('unshow_date', models.DateTimeField(blank=True, null=True, verbose_name='不显示时间')),
                ('status', models.NullBooleanField(choices=[(True, '项目在回收站中'), (None, '项目已被抛弃'), (False, '项目已被还原')], default=True, verbose_name='数据状态')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuukann.Img', verbose_name='所属图片')),
                ('kouza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.KouZa', verbose_name='所属用户')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuukann.Pic', verbose_name='所属相册')),
            ],
            managers=[
                ('manager_one', django.db.models.manager.Manager()),
            ],
        ),
    ]
