# Generated by Django 2.0.5 on 2018-08-08 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='false_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 9, 13, 18, 988372, tzinfo=utc), verbose_name='放入时间'),
        ),
    ]
