# Generated by Django 2.0.5 on 2018-08-08 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_auto_20180808_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='false_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 12, 24, 37, 174500, tzinfo=utc), verbose_name='放入时间'),
        ),
    ]
